"""
Django settings for irusheng_admin project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9io10dzb8&+o@e(a0#0+c%t3_zfsww6-q3e^!afplfj^-&yip_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'admin_app',
    'django_crontab'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

#跨域增加忽略
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ( '*' )

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
    'accept',
    # "enctype",
)

ROOT_URLCONF = 'admin_cfg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin_cfg.wsgi.application'


#导入pymysql的模块
import pymysql
#使用mysql数据库
pymysql.install_as_MySQLdb()

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#数据库信息
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE', 'charge_db'),
        'USER': os.environ.get('MYSQL_USER', 'root'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', ''),
        'HOST': os.environ.get('MYSQL_HOST', 'mysql'),
        'PORT': '3306',
        'OPTIONS': { 'init_command': 'SET default_storage_engine=INNODB,character_set_connection=utf8mb4,collation_connection=utf8_unicode_ci;' }
    }
}

TENCENT_OSS_CONFIG = {
    'TENCENT_OSS_SECRET_ID': os.environ.get('TENCENT_OSS_SECRET_ID', ''),
    'TENCENT_OSS_SECRET_KEY': os.environ.get('TENCENT_OSS_SECRET_KEY', ''),
    'TENCENT_OSS_BUCKET': os.environ.get('TENCENT_OSS_BUCKET', 'smartcharge-1257596698'),
    'TENCENT_OSS_REGION': os.environ.get('TENCENT_OSS_REGION', 'ap-shanghai'),
    'TENCENT_OSS_TOKEN': os.environ.get('TENCENT_OSS_TOKEN', ''),
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
 'default': {
  'BACKEND': 'django.core.cache.backends.dummy.DummyCache',  # 缓存后台使用的引擎
  'TIMEOUT': 1,            # 缓存超时时间（默认300秒，None表示永不过期，0表示立即过期）
  'OPTIONS':{
   'MAX_ENTRIES': 1,          # 最大缓存记录的数量（默认300）
   'CULL_FREQUENCY': 1,          # 缓存到达最大个数之后，剔除缓存个数的比例，即：1/CULL_FREQUENCY（默认3）
  },
 }
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/


NO_AUTH_API = [
    '/api/mum/home',
]

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


# session 设置
SESSION_COOKIE_AGE = 13800 # 单位是秒
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # 关闭浏览器，则COOKIE失效

#文件上传大小最大限制
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600#最大100M


# APP的API地址
APP_API = "https://cdz.lianqiaoiot.com"

# wxurl
HARDWARE_API = "https://smartcharge.pinmait.com/api/hardware/A2S"

ADMIN_WEBSITE= "https://bdcharge-admin.pinmait.com"

# 小程序配置
# WX_XCX_APP_ID = "wxc0b42dc374c5b90b"
# WX_XCX_SECRET = "9e356ccb4c5176db0661986a1ba704d9"
WX_XCX_APP_ID = "wxed9559c9c99d2798"
WX_XCX_SECRET = "4ec18fab1cc7a47e3b99cec2ea0d7a43"


# 文件上传相对目录
FILE_UPLOAD_RELATIVE_DIR = '/static/upload/'
# 文件上传目录
FILE_UPLOAD_DIR = f'{BASE_DIR}{FILE_UPLOAD_RELATIVE_DIR}'

#物联网卡配置信息
USERNAME = "hnbude"
PASSWORD = "5I2@J4@u"
URL = "https://api.tibiot.com/api/v1/card/queryCardInfo"
