version: "3"
services:

  redis:
    image: redis:latest
    command: redis-server --requirepass 11223344root
    ports:
      - 6379:6379
    networks:
      - web-network
    logging:
      driver: "json-file"
      options:
        max-size: "1g"

  tcp_server:
    restart: always
    build: ./TcpSelectServer
    ports:
      - 6999:6999
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./TcpSelectServer:/app
    networks:
      - web-network
    command: python termmain.py
    logging:
      driver: "json-file"
      options:
        max-size: "5g"

  smartchargeadmin:
    restart: always
    build: ./SmartChargeAdmin
    #image: kfrural_django_admin
    ports:
      - 28001:28001
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./SmartChargeAdmin:/app
    command: uwsgi --ini uwsgi.ini
    networks:
      - web-network
    logging:
      driver: "json-file"
      options:
        max-size: "1g"

  smartchargebd:
    restart: always
    build: ./SmartChargeBD
    ports:
      - 28004:28004
    environment:     
      - TZ=Asia/Shanghai
    volumes:
      - ./SmartChargeBD:/app
    command: bash -c "service cron restart && python manage.py crontab add && uwsgi --ini uwsgi.ini"
    networks:
      - web-network

    logging:
      driver: "json-file"
      options:
        max-size: "1g"





networks:
  web-network:
    driver: bridge
