"""
Django settings for SmartCharge project.

Generated by 'django-admin startproject' using Django 2.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import pymysql

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n5=s-503cl9nrzj3fn&vm*rxxbyjtybbxshtycr91dyz7l2xla'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django_crontab',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'charge.apps.ChargeConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SmartChargeBD.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartChargeBD.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
pymysql.install_as_MySQLdb()
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'smart_charge',
        'USER': 'root',
        'PASSWORD': 'Smartcharge_2021',
        'HOST': 'db',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': 'SET default_storage_engine=INNODB,character_set_connection=utf8mb4,collation_connection=utf8_unicode_ci;'}
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# 不需要授权的接口配置
NO_AUTH_API = {
    'user': ['login', 'register'],
    'charge': [],
    'demo': ['test'],
    'test': ['test_set_price_mode'],
    'devops': ['login']
}


# 根API
ROOT_API = "https://cdz.lianqiaoiot.com"


# token过期时间（秒）
# TOKEN_EXP_TIME = 1 * 24 * 60 * 60
TOKEN_EXP_TIME = 2 * 60


# 小程序app_id
WX_XCX_APP_ID = ""
# 小程序secret
WX_XCX_SECRET = ""
# 小程序token过期时间（秒）
WX_XCX_TOKEN_EXP_TIME = 1 * 24 * 60 * 60


# todo 微信公众号app_id
WX_APP_ID = ""
# 微信公众号secret
WX_APP_SECRET = ""
# 微信公众号TOKEN
WX_TOKEN = ""


# 运维小程序app_id
WX_YW_XCX_APP_ID = ""
# 运维小程序secret
WX_YW_XCX_SECRET = ""


# 微信支付相关参数
# 微信支付商户号
WX_PAY_MCH_ID = ""
# 微信支付证书私钥
WX_PAY_PRIVATE_KEY = """
"""
# 微信支付证书序列号
WX_PAY_CERT_SERIAL_NO = ""
# 微信支付APIv3密钥
WX_PAY_APIV3_KEY = ""
# 微信支付回调地址
WX_PAY_NOTIFY_URL = f"{ROOT_API}/api/wx-pay-notice"

# 定时任务
CRONJOBS = [
    ('* * * * *', 'charge.shell.handle_cmd.main', '>>/app/logs/handle_cmd.log'),
    ('* * * * *', 'charge.shell.do_send_wx_temp_msg.main'),
]
# 定时任务如果同一作业的旧实例仍在运行，则阻止启动作业
CRONTAB_LOCK_JOBS = True
# 设置定时任务print打印不缓存（类似python -u xxx.py）
CRONTAB_COMMAND_PREFIX = 'PYTHONUNBUFFERED=1'

# 文件上传相对目录
FILE_UPLOAD_RELATIVE_DIR = '/static/upload/'
# 文件上传目录
FILE_UPLOAD_DIR = f'{BASE_DIR}{FILE_UPLOAD_RELATIVE_DIR}'

